### ISSUE TITLE
left+right click or left+scrooll button push unregister ZoomEnd and ZoomStart events

### ISSUE THREAD

**Issue by vmikeska** [d3/d3#2393] opened 2015-04-14 12:15 UTC
I experienced a problem with zoom behavior.

When on a object where zoom behavior is registered:
Case 1
1. push left and right button at once
2. move with mouse
3. release all the buttons
= ZoomStart and ZoomEnd handlers are unregistered - not being called anymore.

Case 2
1. click to zoom button and left button
2. move with mouse
3. release all the buttons
= ZoomStart and ZoomEnd handlers are unregistered - not being called anymore.

!Zoom handler is still working!

Any ideas how to prevent this behavior ?

Experienced with Chrome: Version 41.0.2272.101 m

Many thanks
Vaclav

**Comment by fridaymeng** [comment] 2015-04-15 02:43
zoom event not released.

**Comment by vmikeska** [comment] 2015-04-15 08:04
If it wasn't clear from the description, of course I release the buttons then. And since then it doesn't work. My other colleagues experienced the same problem on other machines with other D3 apps.

Edited in original description

**Comment by fridaymeng** [comment] 2015-04-15 09:02
i mean the default zoom event,not button event

**Comment by mbostock** [comment] 2015-12-03 18:06
This sounds like a duplicate of #1627.

**Closed** 2017-01-06 17:24 UTC
