### ISSUE TITLE
child_process and fs module error in D3 latest version.

### ISSUE THREAD

**Issue by akbansal** [d3/d3#3140] opened 2017-09-06 19:20 UTC
Latest version 4.10.2 uses d3-request which internally uses xmlhttprequest module and there we are getting below error for child_process and fs module.

```
Module not found: Error: Cannot resolve module 'child_process' in ../node_modules/xmlhttprequest/lib
22:23:09  @ ./~/xmlhttprequest/lib/XMLHttpRequest.js 15:12-36
```

Now reverting back the d3 version to 4.10.0 solved my problem and now my project does not have dependency on these modules. 

Please check and correct this issue in latest version of D3 (4.10.2).

**Comment by mbostock** [comment] 2017-09-06 19:22
Closing as duplicate of d3/d3-request#24. It looks like you were depending on unsupported entry points in the package.json; you’ll need to reconfigure your bundler to consume the code intended for browsers rather than for Node, preferably by consuming the ES modules (the `module` field in the package.json).

**Closed by mbostock** 2017-09-06 19:22 UTC
