### ISSUE TITLE
Different transform attributes between circles and texts

### ISSUE THREAD

**Issue by anthonypzu** [d3/d3#3150] opened 2017-10-12 14:01 UTC
Hello ! I have created circles and texts into elements to can wrap my text inside the circle. I have a problem with the coordonates of my texts. I would like to apply the same transform attributes between circle and text but i can't access to circle transform attributes.

Here is my code:
`var width = 1000,
height = 1300,
radius = 2000,
side = 2 * radius * Math.cos(Math.PI / 4),
dx = radius - side / 2;

console.log("Side" + side);
console.log("dx" + dx);

var svg = d3.select('body').append('svg')
.attr('width', width)
.attr('height', height)
margin = 20,
diameter = +svg.attr("width");

var color2 = d3.scaleOrdinal(d3.schemeCategory10)
.domain(d3.range(9));

var color = d3.scaleLinear()
.domain([-1, 5])
.range(["hsl(152,80%,80%)", "hsl(228,30%,40%)"])
.interpolate(d3.interpolateHcl);

var pack = d3.pack()
.size([diameter - margin, diameter - margin])
.padding(2);

d3.select("body")
.style("background", "white")
.on("dblclick", function() { zoom(root); });

d3.json("{% static 'js/graph_3.json' %}", function(error, root) {
if (error) throw error;

root = d3.hierarchy(root)
.sum(function(d) { return d.size; })
.sort(function(a, b) { return b.value - a.value; });

var focus = root,
nodes = pack(root).descendants(),
view;
var elem = svg.selectAll("g")
.data(nodes);
elemEnter = elem.enter().append("g").attr('transform', 'translate(' + [ dx, dx ] + ')');

var circle = elemEnter.append("circle")
// .attr('x', function(d){return d.x;})
// .attr('y', function(d){return d.y;})
.attr('r', function(d){return d.r;})
.attr("class", function(d) {
if (d.depth === 0) {
return "node node-root";
}
else if (d.depth === 1) {
return "node node-children";
}
else if (d.depth === 2) {
return "node node--questions";
} else {
return "node node--answers";
}
})
.attr("transform", function(d) { console.log(d);return "translate(" + (d.x) + "," + (d.y) + ")"; })
.style("fill", function(d) { if (d.data.name === "flare") {
return "white";} else if (d.depth === 1) {return color2(d.data.main_tag);} else {return d.children ? "" : null; }})
.on("click", clickFct);

function clickFct(d,i) {

if (d3.select(this).classed("node--questions")) {
// alert("fuck");
// alert(d.data.name);

} else {
// console.log(d);
if (focus !== d)
{

    zoom(d); 
    d3.event.stopPropagation();
}
}
}

d3.selectAll('.node--answers')
  .style("display", "none")
d3.selectAll('.node--questions')
  .style("display", "none")
var text = elemEnter.append("foreignObject")
.attr("width", 70)
.attr("height", 70)
.attr("transform", function(d) { console.log(d);return "translate(" + (d.x - dx) + "," + (d.y - dx) + ")"; })
.style("text-anchor", "middle")
.text(function(d){return d.data.name})
.attr("class", function(d) {
if (d.depth === 0) {
return "text text-root";
}
else if (d.depth === 1) {
return "text text-children";
}
else if (d.depth === 2) {
return "text text--questions";
} else {
return "text text--answers";
}
})

d3.selectAll('.text--answers')
.style("display", "none")
d3.selectAll('.text--questions')
.style("display", "none")

var node = elemEnter.selectAll("circle,text");

svg
.style("background", "white")
.on("click", function() { zoom(root); });

zoomTo([root.x, root.y, root.r * 2 + margin]);

function zoom(d) {

var focus0 = focus; focus = d;

var transition = d3.transition()
    .duration(d3.event.altKey ? 7500 : 750)
    .tween("zoom", function(d) {
      var i = d3.interpolateZoom(view, [focus.x, focus.y, focus.r * 2 + margin]);
      return function(t) { zoomTo(i(t)); };
    });

transition.selectAll("text")
  .filter(function(d) { return d.parent === focus || this.style.display === "inline"; })
    .style("fill-opacity", function(d) { return d.parent === focus ? 1 : 0; })
    .on("start", function(d) { if (d.parent === focus) this.style.display = "inline"; })
    .on("end", function(d) { if (d.parent !== focus) this.style.display = "none"; });
  if (focus.depth === 1) {
    d3.selectAll('.node--questions')
      .style("display", "inline");
    d3.selectAll('.node--answers')
      .style("display", "none");
      d3.selectAll('.text--questions')
      .style("display", "inline");
  } else if (focus.depth === 2) {
      d3.selectAll('.node--answers')
      .style("display", "inline");
  }
  else {
    d3.selectAll('.node--questions')
      .style("display", "none");
    d3.selectAll('.node--root')
      .style("background-color", "white");
  }
}

function zoomTo(v) {
var k = diameter / v[2]; view = v;
node.attr("transform", function(d) { return "translate(" + (d.x - v[0]) * k + "," + (d.y - v[1]) * k + ")"; });
circle.attr("r", function(d) { return d.r * k; });
}
});`

**Comment by mbostock** [comment] 2017-10-12 15:11
Duplicate of d3/d3-zoom#117. Please do not cross-post.

**Closed by mbostock** 2017-10-12 15:11 UTC
