### ISSUE TITLE
Clarify ranges of hcl components in docs?

### ISSUE THREAD

**Issue by albell** [d3/d3#2882] opened 2016-06-30 21:24 UTC
The v3 docs say:

https://github.com/d3/d3-3.x-api-reference/blob/master/Colors.md#d3_hcl

> **d3.hcl(h, c, l)**
> 
> Constructs a new HCL color with the specified hue h, chroma c, and luminance l. The hue must be a number in the range [0,360]. The chroma and luminance must be in the range 0,1. These values are available as the h, c, and l attributes of the returned object.

This doesn't seem to be accurate though. Luminance goes from 0 to 100. Chroma goes from 0 to ???. And Hue can return a negative number! (?) Screenshot from console:

<img width="860" alt="d3-v3-hcl-console" src="https://cloud.githubusercontent.com/assets/1142025/16504672/d25f2c06-3ede-11e6-8d37-e0f875197a8f.png">

FWIW the new v4 docs seem to be even less clear on the subject of colorspace "endpoints". For example, does saturation in Cubehelix really go from 0 to 2, as in the <a href="http://bl.ocks.org/mbostock/ba8d75e45794c27168b5">picker demo</a>?

I'm probably misunderstanding here. Either way, the docs might benefit from a bit of clarification. Thanks again Mike.

**Comment by mbostock** [comment] 2016-06-30 21:34
Duplicate of d3/d3-color#24.

The hue should be in the range [0,360). 3.x used the range [-180,+180] instead, but it’s equivalent.

I’m not sure there are well-defined upper bounds for the chroma and luminance channels. The same is true for saturation in the Cubehelix color space—it can be arbitrarily high. (The picker uses 2 as an upper bound because anything above 1 *can* be out-of-gamut in RGB color space.)

**Closed by mbostock** 2016-06-30 21:34 UTC
