### ISSUE TITLE
Feature request: line wrap

### ISSUE THREAD

**Issue by wytrych** [d3/d3#2962] opened 2016-08-31 07:59 UTC
For me a common issue is to add some manual line breaking for long text, due to lack of that in SVG. I think it would be a good feature to have in d3. I have an idea for a good solution and would be happy to submit a PR if you think it's worth it. I was thinking something along these lines:

```
var wrap = d3.lineWrap()
    .maxLength(30)
    .minLastWordLength(2)
    .dy(10)
    .direction(d3.lineWrapExpandBottom);

element.append('text')
        .text(wrap("My very long multline text text text text text"));
```
That would generate something like:
```
<text>
    <tspan dy="0" x="0">My very long multine text</tspan>
    <tspan dy="10" x="0">text text text text</tspan>
</text>
```

The `direction` setting would be used to determine where the fixed position point is, a bit similar to `text-anchor` just vertical.

**Comment by curran** [comment] 2016-08-31 14:05
There is a third party module that implements nice text wrapping functionality for use with D3 https://github.com/d3plus/d3plus-text

**Comment by mbostock** [comment] 2016-08-31 14:44
Duplicate of #1642. See also http://bl.ocks.org/mbostock/7555321

**Closed by mbostock** 2016-08-31 14:44 UTC
