### ISSUE TITLE
README.md issue: skypack.dev seems to not be resolving `d3@7` correctly

### ISSUE THREAD

**Issue by cscheid** [d3/d3#3611] opened 2022-12-12 19:07 UTC
(I think this is the right place to report, since the issue is on this repo. I did read the warning on the issue creator, but I think this applies. Sorry if it doesn't!)

It seems that `skypack.dev` is refusing to build d3 7.7 :(

```html
<html>
  <head>
    <script type="module">
      import * as d3 from "https://cdn.skypack.dev/d3@7";
      const div = d3.selectAll("div");
      </script>
    </head>
  <body></body>
</html>
```

This is what I get in the console on Chrome 108.0.5359.98 on Ventura 13.0.1 (22A400)

```
build:d3@v7.7.0-bA10BcqHRoGFDOMeGCpC:14 [Package Error] "d3@v7.7.0" could not be built. 
[1/5] Verifying package is valid…
[2/5] Installing dependencies from npm…
No matching version found for d3@7.7.0.
```

using `d3@6` on skypack works fine. FWIW, esm.sh does work for both `@6` and `@7`:

```
import * as d3 from "https://esm.sh/d3@7";
```

**Comment by mbostock** [comment] 2022-12-12 19:09
Duplicate of #3607.

See https://github.com/skypackjs/skypack-cdn/issues/332. But it seems that Skypack is no longer maintained.

**Closed by mbostock** 2022-12-12 19:09 UTC
