### ISSUE TITLE
GeoStream is not assignable to parameter of type 'GeoRawProjection' in d3 API version 4

### ISSUE THREAD

**Issue by Huang9495** [d3/d3#3136] opened 2017-08-25 08:39 UTC
**In d3.geo API 3, it has the function to project the geo location coordinates onto the map like leaflet.**

**for example the code in version 3 is like**

var transform = d3.geo.transform({point: self.projectPoint});
self._path = d3.geo.path().projection(transform);

projectPoint: function(x, y) {
    var point = MELBPARKING.Map.map.latLngToLayerPoint(new L.LatLng(y, x));
    this.stream.point(point.x, point.y);
}

**Now I use the angular2 framework to build the leaflet map to project the coordinates in D3.js, the D3.js 's API is built upon the version 4. I looked into the D3.js 's library, the geoTransform and geoProjection are exported**

export {default as geoTransform} from "./src/transform";
export {default as geoProjection, projectionMutator as geoProjectionMutator} from "./src/projection/index";

**In my angular2 project, I used d3.js and leaflet.js to build a leaflet map component, shown as below**

import * as L from 'leaflet';
import * as d3 from 'd3';
import {geoTransform,geoProjection} from "d3-geo";

export class MapsComponent implements OnInit {
    map;
    _path ;

    ngOnInit(){
    console.log('init map');
          his.map = L.map('mapid', {
          center: L.latLng(38, 15),
          zoom: 5,
          });
    this.map.setView(L.latLng(-37.81108500, 144.96269970), 18);
    var self = this;
    var transform = geoTransform({point: self.projectPoint})
    console.log(transform);
    self._path = geoProjection(transform);
    }

    projectPoint(x, y) {
         var point = this.map.latLngToLayerPoint(new L.LatLng(y,x));
         this.map.stream.point(point.x, point.y);
    }
}

**However the project met an error as below**

ERROR in /maps.component.ts (87,32): Argument of type '{ stream(s: GeoStream): { point: (x: any, y: any) => void; } & GeoStream; }' is not assignable to parameter of type 'GeoRawProjection'.
Type '{ stream(s: GeoStream): { point: (x: any, y: any) => void; } & GeoStream; }' provides no match for the signature '(lambda: number, phi: number): [number, number]'.

**what is the wrong**

**Comment by Fil** [comment] 2017-08-25 09:57
please close this issue, a duplicate of https://github.com/d3/d3-geo/issues/111

**Closed** 2017-08-25 13:45 UTC
