### ISSUE TITLE
Cannot customize brush handles

### ISSUE THREAD

**Issue by mblandfo** [d3/d3#2959] opened 2016-08-29 20:45 UTC
In d3v3, as seen here, the handles are "g" elements: https://bl.ocks.org/mbostock/4349545

However, in d3v4, the handles are now rect elements: https://github.com/d3/d3-brush/blob/master/README.md#brush

The rect element cannot have a graphical child, and you cannot add path elements with class handle or it will crash.

I do notice that I can do this:

`bg.selectAll('.handle').attr('rx', 30).attr('ry', 30).attr('fill', 'black').style('height', 20);`

But that changes the resize location and also has limited options. For example I can't make it look like a grabber with lines in the middle.

http://stackoverflow.com/questions/38833274/adding-custom-brush-handles-in-d3-v4

**Comment by mbostock** [comment] 2016-08-29 21:10
Duplicate of d3/d3-brush#14.

**Closed by mbostock** 2016-08-29 21:10 UTC
