### ISSUE TITLE
Feature request: Independent X and Y zoom

### ISSUE THREAD

**Issue by ashwinmr** [d3/d3#3503] opened 2021-06-06 04:54 UTC
I'm trying to use d3 as an alternative to matplotlib or matlab.

It doesn't seem to be possible to constrain the zoom to either x or y axis, without using the brush feature.

Can this be implemented using separate scale for x and y in the transform?

I'm currently using a hack to get this functionality. I store a separate transform for x and y axis. When there is an event, I use the event transform to update my two stored transforms.
```js
    // Handle zoom pan event
    onZoomPan(e){

        // Zoom only x
        if(this.keyLogger.keyDown['x']){
            // Update stored x transform
            this.transformX = d3.zoomIdentity.translate(e.transform['x'],0)
                .scale(this.transformX['k']*e.transform['k']/this.transformKprev)
            // Reset d3 y transform to stored value
            e.transform['y'] = this.transformY['y']
        }
        // Zoom only y
        else if(this.keyLogger.keyDown['y']){
            // Update stored y transform
            this.transformY = d3.zoomIdentity.translate(0,e.transform['y'])
                .scale(this.transformY['k']*e.transform['k']/this.transformKprev)
            // Reset d3 x transform to stored value
            e.transform['x'] = this.transformX['x']
        }
        // Zoom both x and y
        else{
            this.transformX = d3.zoomIdentity.translate(e.transform['x'],0)
                .scale(this.transformX['k']*e.transform['k']/this.transformKprev)
            this.transformY = d3.zoomIdentity.translate(0,e.transform['y'])
                .scale(this.transformY['k']*e.transform['k']/this.transformKprev)
        }
        // Update previous scale value
        this.transformKprev = e.transform['k']

        // Update scale
        var xScaleNew = this.transformX.rescaleX(this.xScale)
        var yScaleNew = this.transformY.rescaleY(this.yScale)

        this.updateScale(xScaleNew,yScaleNew)
    }
```

**Comment by Fil** [comment] 2021-06-06 09:46
Yes, this is the recommend method at the moment.

(Duplicate of https://github.com/d3/d3-zoom/issues/48)

**Closed by Fil** 2021-06-06 09:46 UTC
