### ISSUE TITLE
There is a problem with voronoi method. 

### ISSUE THREAD

**Issue by BauyrzhanBeeMap** [d3/d3#3270] opened 2018-03-01 10:44 UTC
Before I have this pull of polygons
![before_polys](https://user-images.githubusercontent.com/36954546/36840845-a8744d46-1d70-11e8-9607-4f4b126d420c.png)
Now I have this pull of polygons
![actual_polys](https://user-images.githubusercontent.com/36954546/36840878-c2156ae6-1d70-11e8-845f-733d1a0a18cd.png)
I didn't change the code.

**Comment by mbostock** [comment] 2018-03-01 18:49
Duplicate of d3/d3-voronoi#24. You may be able to fix this by adding a small amount of random jitter to your points. The long-term fix is to replace with d3-voronoi implementation to use [delaunator](https://github.com/mapbox/delaunator) and [voronator](https://github.com/observablehq/voronator); see [this prototype](https://beta.observablehq.com/@mbostock/delaunay-voronoi).

**Closed by mbostock** 2018-03-01 18:49 UTC
