### ISSUE TITLE
d3.layout.pack overlap with widely varying numbers

### ISSUE THREAD

**Issue by mpersing** [d3/d3#2868] opened 2016-06-27 17:46 UTC
When values are varying by a very large amount in a given level of a hierarchy when using d3.layout.pack, circles can overlap. A simple reproduction of the issue is [here](https://bl.ocks.org/mpersing/88ce513cd210f58639ae7204a0497fd8).

**Comment by mbostock** [comment] 2016-06-27 17:56
Duplicate of #1761. This is fixed in 4.0;

[![screen shot 2016-06-27 at 10 55 16 am](https://cloud.githubusercontent.com/assets/230541/16390044/a8eae9e0-3c55-11e6-8372-4dfc867f007d.png)](http://bl.ocks.org/mbostock/01b12226e6c4293dd485ac3e2d279987)

**Closed by mbostock** 2016-06-27 17:56 UTC
