### ISSUE TITLE
d3.geo version (6.1.1) bug report

### ISSUE THREAD

**Issue by zdl361** [d3/d3#3445] opened 2020-09-19 08:57 UTC
# Bug in d3.geo version (6.1.1)
hello, 
There is a problem with the d3.geo(v6.1.1) module. Some region are mapped into big rectangles.
#### d3.geo(d3 v5) works fine.
![d3 5](https://user-images.githubusercontent.com/71546076/93662984-d9b57980-fa53-11ea-9d41-b7e7056a49d0.png)
#### But d3.geo(d3 v6.1.1) doesn't work. Some region(海南省,台湾省,湖北省) are mapped into big rectangles.
![image](https://user-images.githubusercontent.com/71546076/93663087-ae7f5a00-fa54-11ea-8ce5-7a9e103f9abc.png)
#### Related code and GeoJson
[htdocs.zip](https://github.com/d3/d3/files/5249382/htdocs.zip)

**Comment by curran** [comment] 2020-09-19 13:06
It would be useful to put the code into a hosted platform like Observable, CodePen, CodeSandbox, bl.ocks.org, anything so that we can see it running without a local setup. Thanks!

**Comment by zdl361** [comment] 2020-09-19 14:24
> It would be useful to put the code into a hosted platform like Observable, CodePen, CodeSandbox, bl.ocks.org, anything so that we can see it running without a local setup. Thanks!

https://observablehq.com/@zdl361/untitled

Bug can be reproduced.

**Comment by Fil** [comment] 2020-09-19 15:03
Duplicate of https://github.com/d3/d3-geo/issues/215

**Closed by Fil** 2020-09-19 15:03 UTC
