### ISSUE TITLE
selection.transition() is not a function when using general d3 namespace

### ISSUE THREAD

**Issue by k-i-m** [d3/d3#3262] opened 2018-02-07 15:23 UTC
After upgrading to d3 v 4.12, all transitions called on selections report an error "transition() is not a function".
This applies when importing entire d3 into a namespace (import * as d3 from 'd3');

**Comment by mbostock** [comment] 2018-02-07 18:50
Duplicate of d3/d3#3256. Possible fixes: 1. Upgrade to 5.0. 2. Use the D3 modules directly rather than the `d3` default bundle. 3. Use your package manager, e.g., yarn’s resolutions feature, to pin the versions of the D3 modules so they are consistent with the `d3` package you are using.

**Closed by mbostock** 2018-02-07 18:50 UTC

**Comment by AKlaus** [comment] 2018-04-15 10:44
@mbostock, I have the exact same error but under different conditions:
 - Version v5.0.0 of the bundle, so `d3-selection: 1.3.0`, `d3-transition: 1.1.1`;
 - I import just certain modules (not `import * as d3 from 'd3';`):
```
import { axisBottom, axisLeft } from 'd3-axis';
import { scaleBand, ScaleBand, scaleLinear, ScaleLinear } from 'd3-scale';
import { BaseType, select, Selection } from 'd3-selection';
import { transition } from 'd3-transition';
```
 - I'm using strong types in TypeScript and have no compilation error

Checked that `package-lock.json` doesn't have references to older versions of the packages., so it's unlikely d3/d3#3256 bug. Also tried installing modules directly, but with no joy.
Upgrading to v5.0.2 is not an option as it hasn't been released as yet.

Of course, after `import * as d3 from 'd3';` and selecting via `d3.select()` make it works. 
What package am I missing?

**Comment by subramaniyanan176** [comment] 2018-04-20 13:58
I am also facing same error as reported above.

**Comment by nitinanand27** [comment] 2018-04-30 12:41
Hi- i'm having same issue with **selection.transition( )**  any help would be appreciated

Error Message on Mouseover:- _ERROR TypeError: tooltip_1.transition is not a function
    at SVGCircleElement.eval (line-chart.component.ts:278)
    at SVGCircleElement.eval (on.js:27)
    at ZoneDelegate.invokeTask (zone.js:398)
    at Object.onInvokeTask (core.js:4724)
    at ZoneDelegate.invokeTask (zone.js:397)
    at Zone.runTask (zone.js:165)
    at SVGCircleElement.ZoneTask.invoke (zone.js:460)

version:- d3: 4.9.1     @types/d3: 4.8.0     d3-transition: 1.1.1       d3-selection: 1.2.0

Code 
import { config } from 'app/config';
import * as d3 from 'd3';
import * as d3Selection from 'd3-selection';
import * as d3Scale from 'd3-scale';
import * as d3Axis from 'd3-axis';
import * as d3Shape from 'd3-shape';
import * as d3Array from 'd3-array';
import * as d3Format from 'd3-format';
import * as moment from 'moment';

  @ViewChild('chart') private **chartContainer**: ElementRef;

      private **tooltip**: any;

    this.tooltip = d3.select(element).append('div')
      .attr('class', 'tooltip')
      .style('opacity', 0);

      const **tooltip** = d3.select(this.chartContainer.nativeElement).selectAll('.tooltip');
                .....................
                       .on('mouseover', function (d) {
              **tooltip.transition()** //error here
                .duration(400)
                .style('opacity', 1);
              tooltip.html(
                site.headline + ' ' + (d.y > 1 ? d.y.toFixed(0) : d.y.toFixed(3))
              )
                .style('left', (d.posX - 40) + 'px')
                .style('top', (d.posY + 40) + 'px');
            })
            .on('mouseout', function (d) {
              tooltip.transition()
                .duration(500)
                .style('opacity', 0);
            });
        });

**Comment by duhaime** [comment] 2019-09-09 15:30
I also ended up here and needed to:

```javascript
import { select } from 'd3-selection';
import transition from 'd3-transition';

select('rect').transition() // ...
```

**Comment by carlavdb** [comment] 2022-07-22 14:39
I know this issue is closed, but I struggled for a very long time to get it sorted. My solution was to recreate my code in CodeSandbox and figure out the dependency versions. For my specific case, the versions that solved the issue was:
```
d3-scale - v4.0.2
d3-scale-chromatic - v3.0.0
d3-selection - v3.0.0
d3-shape - v3.1.0
```
Funny enough, I don't know how `d3-scale-chromatic` and `d3-selection` are connected, but my issue was only resolved once I changed the `d3-scale-chromatic` version.

Hopes this helps someone. If my comment is not allowed here, please feel free to remove it. Thanks

**Comment by jayaramkasi** [comment] 2023-07-28 06:39
If this helps anyone, I was able to get it working when I slightly modified @duhaime 's solution

`
import {transition} from "d3-transition";
`

and then inside the code, since eslint-unused-vars was on for me,
`
transition();
`

Apologies for commenting on a closed issue, feel free to remove it
