### ISSUE TITLE
bl.ocks 4600693 is broken

### ISSUE THREAD

**Issue by kylezeeuwen** [d3/d3#2906] opened 2016-07-17 09:02 UTC
steps to reproduce:

View https://bl.ocks.org/mbostock/4600693 in Chrome 51.0.2704.106 (64-bit) on OSX 10.11.5.

JS Error:

d3.v3.min.js:4 Uncaught TypeError: Cannot read property 'weight' of undefined

**Comment by curran** [comment] 2016-07-17 13:33
It is not broken in Chrome 49.0.2623.112 (64-bit) on OSX 10.6.8.

Must be caused by some change in Chrome between these versions.

**Comment by mbostock** [comment] 2016-07-17 13:37
I pushed a fix this morning and forgot to close this bug. The problem was this example depended on the data file of another example which I hmchanged to demonstrate a new feature in 4.0. I’ll try to avoid cross-example dependencies like this in the future!

**Closed by mbostock** 2016-07-17 13:37 UTC
