### ISSUE TITLE
ArcGIS Javascript API 4.27 and D3.js (ver 7) - multipleDefine errors 

### ISSUE THREAD

**Issue by b2810s** [d3/d3#3764] opened 2023-09-11 18:33 UTC
I have created following sample where I am loading ArcGIS Javascript API 4.27 and D3.js (ver 7) using the Script tag.

https://codepen.io/b2810s/pen/NWebbze

This gives an error on the console related to multipleDefine.

It looks like something to do with the UMD boilerplate of the D3 build conflicting with the Dojo runtime of ArcGIS based on the feedback from https://github.com/d3/d3/discussions/3763. 

Filing an issue here for possible bug in D3.js even though the workaround seems to be changing the order of the script tag.

**Comment by mbostock** [comment] 2023-09-11 19:03
Duplicate of https://github.com/d3/d3/discussions/3763.

**Closed by mbostock** 2023-09-11 19:03 UTC
