### ISSUE TITLE
Feature request; weighted voronoi

### ISSUE THREAD

**Issue by vanderlee** [d3/d3#1893] opened 2014-05-29 12:25 UTC
Weighted voronoi would be great.

As described here: http://en.wikipedia.org/wiki/Weighted_Voronoi_diagram

Each coordinate could take an optional third value which is multiplied with the calculated distance to that coordinate (so the multiplicative variant). Perhaps just an optional extra argument to voronoi() with a index-corresponding array of weights? Would be even more awesome if an option could be supplied to choose whether to use multiplicative or additive weighted. Seems to me if one is implemented, the other can't be much more work.

When looking at the voronoi sourcecode, it very quickly dives into core D3 code, which I know nothing about, so I'm not able to add this myself.

**Comment by mbostock** [comment] 2015-10-21 22:37
https://www.jasondavies.com/power-diagram/
https://www.jasondavies.com/voronoi-treemap/

Might be a nice feature request for [d3-voronoi](https://github.com/d3/d3-voronoi), now.

**Comment by Fil** [comment] 2016-10-02 12:46
This issue could be closed, being a duplicate of https://github.com/d3/d3-voronoi/issues/5 (and https://github.com/d3/d3/issues/2401).

**Comment by mbostock** [comment] 2016-10-02 13:45
Yep. Moved to d3/d3-voronoi#5.

**Closed by mbostock** 2016-10-02 13:45 UTC
Labels: req
